### ISSUE TITLE
Sentences get cut off if semi-colon used

### ISSUE THREAD

**Issue by variadico** [neurosnap/sentences#5]
The following sentence gets cut off after the semi-colon.
```
I am here; you are over there.
```
I tested that sentence at [sentences.erock.io](http://sentences.erock.io/).

All I see is
```
I am here
```

**Comment by neurosnap** [comment]
To clarify, the issue was actually with the sentences demo where I wasn't properly encoding the text that I sent to the http server, the actually sentences library properly handled semicolons.  

Even so, I added a couple unit tests to the sentences library to ensure semicolons are handled properly:

* https://github.com/neurosnap/sentences/blob/master/sentences_test.go#L90
* https://github.com/neurosnap/sentences/blob/master/english/main_test.go#L94  

Thank you for your feedback, much appreciated!
